VillageBuildingReservation/Controllers/BombsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VillageBuildingReservation.Models;

namespace VillageBuildingReservation.Controllers
{
    public class BombsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Bombs
        public ActionResult Index()
        {
            return View(db.Bombs.ToList());
        }

        // GET: Bombs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bombs bombs = db.Bombs.Find(id);
            if (bombs == null)
            {
                return HttpNotFound();
            }
            return View(bombs);
        }

        // GET: Bombs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bombs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Bombs bombs)
        {
            if (ModelState.IsValid)
            {
                if (!String.IsNullOrEmpty(bombs.Name))
                {
                    db.Bombs.Add(bombs);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View(bombs);
        }

        // GET: Bombs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bombs bombs = db.Bombs.Find(id);
            if (bombs == null)
            {
                return HttpNotFound();
            }
            return View(bombs);
        }

        // POST: Bombs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Bombs bombs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bombs).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = MessagingSystem.AddMessage("تم تعديل العتاد بنجاح", "success");
                return RedirectToAction("Index");
            }
            return View(bombs);
        }

        // GET: Bombs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bombs bombs = db.Bombs.Find(id);
            if (bombs == null)
            {
                return HttpNotFound();
            }
            return View(bombs);
        }

        // POST: Bombs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bombs bombs = db.Bombs.Find(id);
            db.Bombs.Remove(bombs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VillageBuildingReservation/Controllers/ReservationsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VillageBuildingReservation.Models;
using VillageBuildingReservation;
using System.Web.UI.WebControls;

namespace VillageBuildingReservation.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reservations
        [HttpGet]
        [Authorize(Roles = "SuperAdmin,admin ,general")]
        public ActionResult Index()
        {
            DateTime CurrentDate = DateTime.Now;
            ReservationVM VM = new ReservationVM();
            VM.Year = CurrentDate.Year;
            VM.Month = CurrentDate.Month;
            VM.Reservations =  db.Reservations.Where(m => m.ReservationDate.Year == VM.Year && m.ReservationDate.Month == VM.Month).OrderBy(x => x.ReservationDate).Include(b=>b.Bombs).Include(b=>b.Blocks).ToList();
            VM.DDlYear = GlobalController.GenerateYearsDDL(VM.Year);
            VM.DDlMonth = GlobalController.GenerateMonthsDDL(VM.Month).ToList() ;
            return View(VM);
        }
        [HttpPost]
        [Authorize(Roles = "admin ,general")]
        public ActionResult Index(ReservationVM VM)
        {
            VM.DDlYear = GlobalController.GenerateYearsDDL(VM.Year);
            VM.DDlMonth = GlobalController.GenerateMonthsDDL(VM.Month).ToList();
            VM.Reservations = db.Reservations.Where(m => m.ReservationDate.Year == VM.Year && m.ReservationDate.Month == VM.Month).OrderBy(x => x.ReservationDate).Include(b => b.Bombs).Include(b => b.Blocks).ToList();
            
            return View(VM);
        }

        // GET: Reservations/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            //var query = (from b in db.blocks
            //             join z in db.zones on b.zoneid equals z.id
            //             select new { b, z }).tolist();
            // ViewBag.listOfBlocks = new SelectList(db.Blocks.Include(Z=>Z.Zone), "Id", "FullBlockName");
            //List<SelectListItem> list  = new List<SelectListItem>();
            //list = (db.Blocks.Include(Z =>Z.Zone).Select(
            //    x => new SelectListItem()
            //    {
            //        Value = x.Id.ToString(),
            //        Text = x.Key + " : "+x.Name
            //    })).ToList() ;
           

            //foreach (ListItem listitem in list)
            //{
            //    Block block = db.Blocks.Find(long.Parse(listitem.Value));
            //    Zone zone = db.Zones.Find(block.ZoneId);
            //    if (zone != null)
            //    {
            //        listitem.Attributes.Add("optiongroup", zone.Name);
            //    }
            //}
            // select last record Id 
            int id = db.Reservations.Max(r => r.Id);
            // get the last reservation
            Reservation reservation = db.Reservations.Find(id);

            List<Block> Blocks = db.Blocks.Include(X => X.Zone).ToList();
            ViewBag.listOfBlocks = Blocks;
            ViewBag.listBombs = new MultiSelectList(db.Bombs, "Id", "Name", GetReservationBombsIds(reservation));
            return View(reservation);
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create(Reservation reservation, List<int> listOfBlocksDDL, List<int> listOfBombsDDL)
        {
            DateTime t1, t2;

            if (ModelState.IsValid)
            {
                List<Block> Blocks = db.Blocks.Include(X => X.Zone).ToList();


                // check  list of blocks 
                //if (listOfBlocksDDL == null || listOfBlocksDDL.Count == 0)
                //{
                //    TempData["message"] = MessagingSystem.AddMessage(GlobalController.overridenRequiredFieldMessage(" المنشأة  "), "danger");
                //    ViewBag.listOfBlocks = Blocks;
                //    return View(reservation);
                //}

                /// Compare start and end time
                if (reservation.StartTime != null && reservation.EndTime != null)
                {
                    t1 = DateTime.Parse(reservation.ReservationDate.ToString("yyyy/MM/dd") + " " + reservation.StartTime.ToString() + ":00.000");
                    t2 = DateTime.Parse(reservation.ReservationDate.ToString("yyyy/MM/dd") + " " + reservation.EndTime.ToString() + ":00.000");

                    if (TimeSpan.Compare(t1.TimeOfDay, t2.TimeOfDay) == 1)
                    {
                        TempData["message"] = MessagingSystem.AddMessage("وقت البدأ يجب ان يكون اصغر من وقت الإنتهاء", "danger");
                        ViewBag.listOfBlocks = Blocks;
                        ViewBag.listBombs = new SelectList(db.Bombs, "Id", "Name");
                        return View(reservation);
                    }
                }
                 else
                {
                    TempData["message"] = MessagingSystem.AddMessage("يحب ادخال وقت البدء و الانتهاء", "danger");
                    ViewBag.listOfBlocks = Blocks;
                    ViewBag.listBombs = new SelectList(db.Bombs, "Id", "Name");
                    return View(reservation);
                }

                //adding selected blocks objects to reservation
                if (listOfBlocksDDL != null && listOfBlocksDDL.Count != 0)
                {
                    listOfBlocksDDL.ForEach(delegate (int BlockId)
                    {
                        reservation.Blocks.Add(db.Blocks.Find(BlockId));
                    });
                }

                //adding selected Bombs objects to reservation

                if (listOfBombsDDL != null && listOfBombsDDL.Count != 0)
                {
                    listOfBombsDDL.ForEach(delegate (int BombId)
                    {
                        reservation.Bombs.Add(db.Bombs.Find(BombId));
                    });
                    //barkya is needed set to true since bombs are checked
                    reservation.IsNeedBarkya = true;
                }

                db.Reservations.Add(reservation);
                db.SaveChanges();
                TempData["message"] = MessagingSystem.AddMessage("تم انشاء الحجز بنجاح", "success");

                return RedirectToAction("Index");
            }

            return View(reservation);
        }

        // GET: Reservations/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            List<Block> Blocks = db.Blocks.Include(X => X.Zone).ToList();
            ViewBag.listOfBlocks = Blocks;
            ViewBag.listBombs = new MultiSelectList(db.Bombs, "Id", "Name", GetReservationBombsIds(reservation));


            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }



        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(Reservation reservation, List<int> listOfBlocksDDL, List<int> listOfBombsDDL)
        {
            DateTime t1, t2;

            if (ModelState.IsValid)
            {
                List<Block> Blocks = db.Blocks.Include(X => X.Zone).ToList();
                ViewBag.listOfBlocks = Blocks;

                db.Entry(reservation).State = EntityState.Modified;
                //if (listOfBlocksDDL == null || listOfBlocksDDL.Count == 0)
                //{
                //    TempData["message"] = MessagingSystem.AddMessage(GlobalController.overridenRequiredFieldMessage(" المنشأة  "), "danger");
                //    return View(reservation);
                //}
                /// Compare start and end time
                if (reservation.StartTime != null && reservation.EndTime != null)
                {
                    t1 = DateTime.Parse(reservation.ReservationDate.ToString("yyyy/MM/dd") + " " + reservation.StartTime.ToString() + ":00.000");
                    t2 = DateTime.Parse(reservation.ReservationDate.ToString("yyyy/MM/dd") + " " + reservation.EndTime.ToString() + ":00.000");

                    if (TimeSpan.Compare(t1.TimeOfDay, t2.TimeOfDay) == 1)
                    {
                        TempData["message"] = MessagingSystem.AddMessage("وقت البدأ يجب ان يكون اصغر من وقت الإنتهاء", "danger");
                        ViewBag.listOfBlocks = Blocks;
                        ViewBag.listBombs = new SelectList(db.Bombs, "Id", "Name");
                        return View(reservation);
                    }
                }
                else
                {

VillageBuildingReservation/Views/Shared/_Layout.cshtml
@using VillageBuildingReservation.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  حجز المباني</title>
    <link rel="shortcut icon" href="~/Media/Village-reservation-favicon.png" />
    @RenderSection("Styles", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <img class="img_headr_left" runat="server" src="~/Media/ma3had.png" />
        <img class="img_headr_right" runat="server" src="~/Media/ma3had.png" />
        <div class="container">
            <div class="navbar-header">


                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <h1 class="app_title">معهد قوى الأمن الداخلي - المدرسة المشتركة  - حجز المباني  </h1>
                <ul class="nav navbar-nav">

                    @if (@Request.IsAuthenticated)
                    {
                        if (User.IsInRole("admin"))
                        {
                            <li>@Html.ActionLink("الاعتدة المستخدمة", "Index", "Bombs", null, new { @class = "listbomblink" })</li>
                            <li>@Html.ActionLink("الحجوزات", "Index", "Reservations", null, new { @class = "listreservationlink" })</li>
                        }
                        else
                        {
                            if (User.IsInRole("general"))
                            {
                                <li>@Html.ActionLink("تقرير الحجوزات", "ReservationReport", "Reservations", null, new { @class = "ReservationReport" })</li>

                            }
                            else
                                    if (User.IsInRole("SuperAdmin"))
                            {
                                <li>@Html.ActionLink("الاعتدة المستخدمة", "Index", "Bombs", null, new { @class = "listbomblink" })</li>
                                <li>@Html.ActionLink("الحجوزات", "Index", "Reservations", null, new { @class = "listreservationlink" })</li>
                                <li>@Html.ActionLink("Add New Password", "AddnewPassword", "Account", null, null)</li>
                                <li>@Html.ActionLink("Register New User", "Register", "Account", null, null)</li>
                                <li>@Html.ActionLink("Manage User Role", "ListOfRoles", "Administration", null, null)</li>
                            }

                        }
                        <li>@Html.ActionLink("خريطة القرية", "VillageMap", "Reservations", null, new { @class = "villagemaplink" })</li>
                    }
                </ul>
                @*if (User.IsInRole("admin"))
                    {
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("التخصص", "Index", "Specifications")</li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("الضباط", "Index", "Officers")</li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("رزنامة الدورات", "Index", "Tournaments")</li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("الرزنامة الأساسية", "Calendar_M_AND_T", "Missions")</li>
                        </ul>
                    }
                    else
                    {
                        if (User.IsInRole("general"))
                        {
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("الضباط", "Index", "Officers")</li>
                            </ul>

                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("الرزنامة الأساسية", "Calendar_M_AND_T", "Missions")</li>
                            </ul>
                        }
                    }*@


                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @{ MessagingSystem msg = (MessagingSystem)TempData["message"];}
        @if (msg != null)
        {
            @Html.Raw(MessagingSystem.GenerateMessage(msg.Message, msg.MessageType))
        }
        @RenderBody()
        <hr />
        @*<footer>
                <p>&copy; @DateTime.Now.Year - Officer Mission</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)

    @Scripts.Render("~/bundles/custom")

</body>
</html>